# fly.toml app configuration file generated for myenergy-hmce on 2025-10-16T13:28:51+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myenergy-hmce'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
