# fly.toml app configuration file generated for myenergy-wlce on 2025-10-16T13:09:20+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myenergy-wlce'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
