# Fly.io configuration for Production environment
# To create the app: fly launch --no-deploy --name myenergy-prod --config fly.prod.toml
# To deploy: fly deploy --config fly.prod.toml

app = 'myenergy-prod'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'  # Keep running for production
  auto_start_machines = true
  min_machines_running = 1     # Always keep at least 1 machine running

[[vm]]
  memory = '256mb'  # Minimal memory for static site
  cpu_kind = 'shared'
  cpus = 1
