name: my_energy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.4.0+1179

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  aligned_tooltip: ^0.0.1
  app_links: ^6.4.1
  app_links_platform_interface: ^2.0.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  cached_network_image_web: ^1.3.1
  collection: ^1.19.1
  data_table_2: ^2.6.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  expandable_text:
  floating_bottom_navigation_bar: ^1.5.2
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  flutter_spinkit: ^5.2.2
  font_awesome_flutter: ^10.9.1
  from_css_color: ^2.0.0
  functions_client: ^2.5.0
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  gotrue: ^2.16.0
  hive: ^2.2.3
  http: ^1.5.0
  intl: ^0.20.2
  json_path: ^0.8.0
  jwt_decode: ^0.3.1
  mask_text_input_formatter: ^2.9.0
  mime_type: ^1.0.1
  package_info_plus: ^9.0.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.19
  path_provider_foundation: ^2.4.2
  path_provider_linux: ^2.2.1
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.3.0
  percent_indicator: ^4.2.5
  postgrest: ^2.5.0
  provider: ^6.1.5+1
  realtime_client: ^2.6.0
  sentry_flutter: ^9.7.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.13
  shared_preferences_foundation: ^2.5.5
  shared_preferences_linux: ^2.4.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: ^2.4.1
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  sqflite: ^2.4.2
  sqflite_common: ^2.5.6
  stop_watch_timer: ^3.2.2
  storage_client: ^2.4.1
  supabase: ^2.10.0
  supabase_flutter: ^2.10.3
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.20
  url_launcher_ios: ^6.3.4
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.3
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4
  web: ^1.1.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.1
  webview_flutter_platform_interface: ^2.14.0
  webview_flutter_web:
  webview_flutter_wkwebview: ^3.23.0
  flutter_svg: ^2.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  http_parser: ^4.1.2

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  objective_c: ^8.1.0
  test_api: ^0.7.7

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  image: ^4.5.4
  lints: ^6.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

