name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      fly_config:
        required: true
        type: string
    secrets:
      FLY_API_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Flutter version
        id: flutter-version
        run: |
          FLUTTER_VERSION=$(cat .flutter-version)
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV
          echo "Flutter version: $FLUTTER_VERSION"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Build Flutter app
        run: bin/build-fly ${{ inputs.environment }}

      - name: Build Docker Image
        id: build_image
        run: docker build -t myenergy:${GITHUB_REF_NAME} .

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@1.5
        with:
          version: 0.3.195

      - name: Get Project version
        id: project-version
        run: |
          PROJECT_VERSION=$(grep '^version=' myenergy.version | cut -d'=' -f2)
          BUILD_NUMBER=$(grep '^build=' myenergy.version | cut -d'=' -f2)
          echo "PROJECT_VERSION=${PROJECT_VERSION}+${BUILD_NUMBER}" >> $GITHUB_ENV

      - name: Deploy to Fly.io
        run: flyctl deploy --config ${{ inputs.fly_config }} --local-only --image myenergy:${GITHUB_REF_NAME}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Commit version file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin ${{ github.event.repository.default_branch }}
          git checkout ${{ github.event.repository.default_branch }}
          git add myenergy.version
          git commit -m "Bump build number after ${{ inputs.environment }} deployment [skip ci]" || echo "No changes to commit"
          git push origin ${{ github.event.repository.default_branch }}
